name: native build
run-name: "[ ${{ github.ref }} ] Branch native Build"
on:
  workflow_dispatch:
  push:
    branches: [ '**' ]
    paths: [ '**' ]

jobs:
  build:
    name: Maven build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile, Test & Build
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          gu --version
          native-image --version
          
          ./mvnw -B spring-boot:build-image \
              -Pnative \
              -Dspring-boot.build-image.imageName=ghcr.io/samit-maersk/${{github.event.repository.name}}:$(date +%d%m%Y%H%M)
          
          docker images -a
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker push
        run: docker push ghcr.io/samit-maersk/${{github.event.repository.name}}
