name: native build
run-name: "[ ${{ github.ref }} ] Branch native Build"
on:
  workflow_dispatch:
  push:
    branches: [ '**' ]
    paths: [ '**' ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile, Test & generate native image
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          gu --version
          native-image --version
          
          ./mvnw -B spring-boot:build-image \
              -Pnative \
              -Dspring-boot.build-image.imageName=ghcr.io/${{ github.actor }}/${{github.event.repository.name}}:$(date +%d%m%Y%H%M)
          
          docker images -a
      - name: Compile, Test & generate native executable
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          gu --version
          native-image --version
          
          ./mvnw -B native:compile
          
          ls -al target/
      -
        name: Login to GitHub Container Registry
        if: matrix.os == 'ubuntu-latest'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker push
        if: matrix.os == 'ubuntu-latest'
        run: docker push -a ghcr.io/samit-maersk/${{github.event.repository.name}}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: target/springboot-3.x.x
